[project]
name = "lab1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=2.15.0",
    "pdoc>=16.0.0",
    "ruff>=0.14.13",
]
